language: node_js
node_js:
  - "4.4.1"
branches:
  only:
    - master
before_install:
  - npm install -g gulp
install:
  - npm install
script: gulp build
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    git clone https://themugh:$GITHUB_API_KEY@github.com/themugh/gabc2016.git deploy-web
    cd deploy-web
    git checkout --orphan gh-pages
    git rm -rf .
    cd ..
    cp -f -R ./dist ./deploy-web
    cd deploy-web
    git add .
    git commit -a -m "deploy"
    # git remote add origin https://themugh:$GITHUB_API_KEY@github.com/themugh/gabc2016.git
    git push -u origin gh-pages
    cd "$TRAVIS_BUILD_DIR"
  fi