language: node_js
node_js:
  - "4.4.1"
branches:
  only:
    - master
before_install:
  - npm install -g gulp
install:
  - npm install
script: gulp build
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd dist
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m "deploy"
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://themugh:$GITHUB_API_KEY@github.com/themugh/gabc2016-gh-pages gh-pages &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi