language: node_js
node_js:
  - "4.4.1"
branches:
  only:
    - master
before_install:
  - npm install -g gulp
install:
  - npm install
script: gulp build
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd dist
    git init
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m "deploy"
    git remote add origin https://github.com/themugh/gabc2016.git
    git push -u origin gh-pages
    cd "$TRAVIS_BUILD_DIR"
  fi